- README.adoc
- templates/slim/document.html.slim
When generating more than one document it should be nice to be able pointing the same folder.
Actually, the reveal.js dir is hardcoded in the document.html.slim and the folder has to be copied in each presentation folder..
addition of a revealjsdir attribute to specify the location of the reveal.js folder.
Based on the work of @dsyer for deckJs asciidoctor/asciidoctor-backends@1b28d98
> Adding ability to change reveal.js path

- README.adoc
- templates/slim/document.html.slim
By default, the 'zenburn' syntax highlighting style from highlight.js
is included with reveal.js and used. But now you can provide
your own path|URL to a custom syntax highlighing style.
eg. one of the many other styles highlight.js offers.
Also corrected the link to the reveal.js theme edit/creation documentation
> Make used highlight style configurable

- templates/slim/document.html.slim
Fixes #26. The changes are pretty straightforward, and follow the convention above of defaulting to the reveal.js defaults.
I didn't add any testing because I don't really know how to do automated testing of something like this, but I did make some slides where I used these features and it worked for me.
> Added width / scale / margins options

- README.adoc
- templates/slim/document.html.slim
- Update list of available themes to match current release
- Update default to be black (default theme of current release)
Also note that in reveal.js-2.6.x there is no css file named league. The
default theme is named default. This means currently no theme is actually
loaded.
This commit fixes the theme for 3.1.x. Unfortuantely, the black theme does
not exist until 3.0.0. This means this commit will break 2.x version of
reveal.js.
> Update to reveal.js 3.1.0 themes

- templates/slim/block_video.html.slim
Fix for videos missing protocol [issue #44]
(https://github.com/asciidoctor/asciidoctor-reveal.js/issues/44)
Added asset_uri_scheme attribute that allows users to specify a
protocol for their YouTube and Vimeo  embeds.
This reflects the latest code in core:
https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/html5.rb#L915-L973
> Fix for videos missing protocol issue #44

- README.adoc
- templates/slim/block_preamble.html.slim
- templates/slim/document.html.slim
As discussed in #49. Thanks for the guidance @mojavelinux. 
`@document.find_by` doesn't work on asciidoctor previous to 1.5.0 so I thought I mentioned minimum requirements in the README.
> document preamble shown only on title slide (fixes #49, #43)

- README.adoc
- templates/slim/section.html.slim
- test/concealed-slide-titles.adoc
Simple fix for issue #20. Thanks to @kubamarchwicki for solution example.
> Hide slide titles: support %notitle and %conceal section options (#20)

- templates/slim/inline_kbd.html.slim
Regarding Asciidoctor's Ruby code, the keyboard sequence element should not be `<kbd>` but `<span>`
Here is the ruby code from [html5.rb](https://github.com/asciidoctor/asciidoctor/blob/ef7d3a113fd9b17470987cde845313a01129529f/lib/asciidoctor/converter/html5.rb) :
```
def inline_kbd node
if (keys = node.attr 'keys').size == 1
%(<kbd>#{keys[0]}</kbd>)
else
key_combo = keys.map {|key| %(<kbd>#{key}</kbd>+) }.join.chop
%(<span class="keyseq">#{key_combo}</span>)
end
end
```
> Replaced <kbd> element with <span> for the keyboard sequence.

- templates/slim/section.html.slim
When working with other languages than English there are often nonlatin characters in section titles. When reveal.js is working with history enabled - this doesn't get resolved to proper navigation links (presentation starts over from the begining)
This is due to this reveal.js issue https://github.com/hakimel/reveal.js/issues/836 which resulted in a following pull request in reveal.js itself https://github.com/hakimel/reveal.js/commit/da82c8ce81a5acc8b14002a5818a32ce0c89f7b8
The important change is 
```
id = id.toLowerCase();
id = id.replace( /[^a-zA-Z0-9\-\_\:\.]/g, '' );
```
which I've added to the section template as well. 
I'm not sure if that's the way it should be done so feedback is appreciated
> Limit named links to [a-zA-Z0-9\-\_\:\.]

- README.adoc
- templates/slim/document.html.slim
- test/customcss.adoc
- test/customcss.css
Check the documentation commit for details.
> :customcss: attribute for easy per-presentation CSS

- templates/jade/embedded.jade
Resolves the following issue with Jade 1.11.0:
```
Error: Jade:6
4| unless !node['$footnotes?']() || node['$attr?']('nofootnotes')
5|   div(id='footnotes')
> 6|     hr
7|       each fn in node.$footnotes()
8|         div.footnote(id='_footnote_' + fn.$index())
9|           a(href='#_footnoteref_' + fn.$index())
hr is self closing and should not have content. (line 6)
```
> hr is self closing and should not have content

- README.adoc
- templates/slim/block_video.html.slim
- templates/slim/section.html.slim
- test/video.adoc
Made several improvements to the support and documentation around videos. Fixes #71.
* background videos on individual slides is supported (w/ shorthand options)
* videos by default will use a saner size (`[.stretch]`)
* everything is documented
The PR is larger than it should because I branched it from `data-background-rework` and rebased it from master before pushing. Once #52 is merged, I'll rebase again on master and reviewing should be a lot more straightforward.
Task list:
> Video support improvements

- templates/slim/section.html.slim
- test/data-background-newstyle.adoc
As reported in #96, a first vertical slide w/o a background should not show the next vertical slide's background.
Here's a fix for it. I'm not 100% satisfied with it (given that it spans for longer than 80 chars) but it works.
Integrated the user-provided test case (and we love those! :+1:).
> Fixed vertical slides and background problem

- templates/slim/section.html.slim
The regex removes the first character of the title in the id, making
== P2P Applications
have "2p-applications" as id, failing in navigation, as it starts with a number.
> Changed regex, so it does not remove first letter of id

- templates/slim/document.html.slim
- templates/slim/helpers.rb
- test/title-preamble.adoc
- test/title-subtitle-partitioning.adoc
See #70. Removed unnecessary HTML tags if no authors are provided too.
> Implemented subtitle partitioning

- README.adoc
Related to discussion in #95. Allows our example to avoid :revealjsdir: document attribute in recent node versions while still allowing per-document overrides.
Took the opportunity to reverse the default value as discussed.
Let me know if it's good for you.
> node: Using @ attribute prefix to lower CLI priority

- templates/slim/section.html.slim
Reveal.js has the concept of [slide states](https://github.com/hakimel/reveal.js/#slide-states), where a slide's value for `data-state` will be applied to the document as a CSS class. With this it is easy to, e.g. give selected slides a distinct style.
The reaveal.js backend does currently not set the state. With the change proposed here, the following works:
```
[data-state="empty"]
=== !
```
Which leads to 
```
<section data-state="empty" class="present"></section>
```
I did not thoroughly check whether this change should also be applied to one of the other templates.
> Add data-state to slides

- README.adoc
- package.json
The idea is to provide a minimal README so that it points to our GitHub README and we don't need to update it too often.
Filed upstream issue: https://github.com/npm/npm/issues/14159
> Added a minimal README for the npm package

- CHANGELOG.adoc
- templates/slim/document.html.slim
Some fancy stuff mind end up outside of slide sections and to give it special treatment on the title slide, the section's CSS class `title` does not suffice. (See a use case [here](http://slides.codefx.org/junit-5/2017-01-25-JUG-Karlsruhe), where the footer only shows from the second slide forward.)
This change applies the data-state `title` to the title slide, making reveal.js apply it as a CSS class to the document when the title slide is active.
> Apply data-state 'title' to the title slide

- asciidoctor-revealjs.gemspec
- templates/slim/block_admonition.html.slim
- templates/slim/block_image.html.slim
- templates/slim/block_listing.html.slim
- templates/slim/section.html.slim
- use attributes[1] to access first positional attribute
- use textlabel to access textual label of admonition block
> resolves #132 fix templates to work with 1.5.6

- examples/history-regression-tests.adoc
- templates/section.html.slim
- test/doctest/concealed-slide-titles.html
- test/doctest/customcss.html
- test/doctest/data-background-newstyle.html
- test/doctest/data-background-oldstyle.html
- test/doctest/document.html
- test/doctest/history-regression-tests.html
- test/doctest/history.html
- test/doctest/images.html
- test/doctest/keyboard-shortcuts.html
- test/doctest/level-sections.html
- test/doctest/multi-destination-content.html
- test/doctest/outline.html
- test/doctest/preamble.html
- test/doctest/revealjs-stretch.html
- test/doctest/section.html
- test/doctest/slide-state.html
- test/doctest/source-callouts.html
- test/doctest/speaker-notes.html
- test/doctest/title-preamble.html
- test/doctest/title-slide-color.html
- test/doctest/title-slide-image.html
- test/doctest/title-slide-video.html
- test/doctest/title-subtitle-partitioning.html
- test/doctest/toc.html
- test/doctest/transitions.html
- test/doctest/vertical-slides.html
- test/doctest/video.html
There were still some problems with the id stripping regex. I created a more extensive test case and made sure to pass all tests.
References:
* #127 
* #99 
* #75 
* hakimel/reveal.js#1346
* #32 
* https://github.com/hakimel/reveal.js/blob/360bc940062711db9b8020ce4e848f6c37014481/js/reveal.js
> Reveal.js compatible slide id generation fixes history feature (#127)

- Rakefile
Added a rake examples:serve task to quickly load and preview examples.
It loads a web server inside the examples/ dir. It doesn't depend on generation (task examples) or build because I didn't know how to do it and I wasn't sure it was necessary.
Created a PR so that people who know better than me can comment.
> Rake examples:serve task

- CHANGELOG.adoc
- README.adoc
- examples/source-callouts.adoc
- templates/listing.html.slim
- test/doctest/source-callouts.html
> Add data-noescape to highlightjs callouts

- examples/source-callouts.adoc
- examples/source-coderay.adoc
- examples/source-highlightjs-html.adoc
- examples/source-highlightjs.adoc
- examples/source-prettify.adoc
- examples/source-pygments.adoc
- test/doctest/source-callouts.html
- test/doctest/source-highlightjs-html.html
- test/doctest/source-highlightjs.html
- test/doctest/source-prettify.html
Related to #167 and #163. Only highlightjs is added to doctest otherwise we will need to add dependencies and I'm not fond of that given what we discussed in #163.
> Added new examples and tests around source code listings

- README.adoc
Let me know if anything is unclear or could be improved.
> doc: Clarified syntax highlighting support (fixes #163)

- README.adoc
Broken link found while reviewing #169, a 1.1.0 regression.
@mojavelinux I would like your opinion on the way I workaround GitHub's *include:: are turned into link:* behavior.
> Fixed the display of include:: links for github and a broken link

- CHANGELOG.adoc
- asciidoctor-revealjs.gemspec
It's not the cleanest thing I've done in Ruby but it works. Reviewers, feel free to refer me to a solution better aligned with Asciidoctor's approach if you have one in mind.
> Adding converter.rb manually in gemspec. Fixes #172

- README.adoc
AsciiDoctor defines the `:imagesdir:` attribute, not `:imagedir:`, fixes this.
> README: fix imagedir -> imagesdir attribute

- README.adoc
- examples/speaker-notes.adoc
- templates/admonition.html.slim
- templates/helpers.rb
- templates/notes.html.slim
- templates/open.html.slim
- templates/sidebar.html.slim
- test/doctest/speaker-notes.html
Added a new `notes` role for speaker notes. Closely maps to upstream terminology. Also expanded valid note blocks to `open` and `sidebar` blocks (in addition to `admonition`).
`speaker` and `aside` roles are still working as valid speaker notes roles on the same block types as `notes`.
In other words, creating speaker notes is easier to remember now.
I did `sidebar` because of bespoke.
> New speaker notes syntax

- README.adoc
- examples/revealjs-plugin-activation.adoc
- templates/document.html.slim
- test/doctest/customcss.html
- test/doctest/document.html
- test/doctest/history-regression-tests.html
- test/doctest/history.html
- test/doctest/revealjs-plugin-activation.html
- test/doctest/revealjs-plugins.html
- test/doctest/theme-custom.html
suggestion for #201 , 
please review, and say if this is OK.
I would like to add a likewise option for enable-plugin-pfd, to be able to load the default pdf plugin without adding it to the custom plugins, but before doing any further adjustment it would be create to get some feedback
> Plugin config2

- README.adoc
- examples/images.adoc
- test/doctest/images.html
New section about Asciidoctor-reveal.js specific roles, took the opportunity to introduce how roles are written in AsciiDoc and linked to upstream docs. Also took care of mentioning that image macro have a slightly different behavior.
Added examples (and tests) too.
Related to the just-added #213
> Clarified in docs and examples what's possible with floating and roles

- examples/source-callouts.adoc
- examples/source-highlightjs.adoc
- templates/listing.html.slim
- test/doctest/colist.html
- test/doctest/listing.html
- test/doctest/multi-destination-content.html
- test/doctest/source-callouts.html
- test/doctest/source-highlightjs-html.html
- test/doctest/source-highlightjs.html
- test/doctest/source-prettify.html
With examples and doctest.
This might break user's customcss if they match on the nesting, we need to advise in release notes / changelog.
> Remove div nesting on listingblocks by default (fixes #195)

- .travis.yml
remove sudo: false (container-based infrastructure) as recommended by Travis
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
> drop sudo: false from Travis CI config

- .travis.yml
- CHANGELOG.adoc
Adding ruby 2.6 and once our 2.0 is released, we will drop older rubies following upstream Asciidoctor's plan.
> Travis: Added Ruby 2.6 as a target

- templates/table.html.slim
- test/doctest/table.html
Removed verse table cells support and tests to keep builds happy.
Asciidoctor 2.0.0 is dropping verse table cells and nobody will miss them. See https://github.com/asciidoctor/asciidoctor/issues/3111 for workarounds if you need one.
> Drop verse table cells and fix tests

- README.adoc
I was positively surprised that setting `:revealjs_height:` just works.
Added three more values an a link to the template source so people
can discover more settings if needed.
> Document further revealjs_* options in README.adoc

- templates/document.html.slim
- test/doctest/revealjs-features.html
Asciidoctor currently does only support/expect attributes to be
in lower case. Unfortunately the code expected attributes like
ealjs_defaultTiming which were never actually resolved and
always provided the default value
> fix: only use lowercase asciidoc attributes

- yarn.lock
Fixes security warnings from github although attack surface is not a concern for most use cases. Yarn is also an undocumented way to use this project. At your own risks.
If CI is green I'm going to merge.
> yarn: updates meant getting rid of tar-fs security issue

- test/js-babel/main.js
- test/js-babel/package-lock.json
- test/js-babel/package.json
Fixes GitHub security warnings. Done in two different commits to see a fixed version with the 1.x javascript API and then the 2.x API.
Thanks @Mogztter for the fixes! This is a backport of https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel/pull/2 and https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel/pull/3. See also https://github.com/Mogztter/asciidoctor-reveal.js-integration-babel/issues/1.
> Babel updates

- .travis.yml
Will merge only once I know I'm doing a feature release. Don't want to drop support on a bugfix release.
> Dropping Ruby 2.1 and 2.2 (End of Life)

- README.adoc
- templates/document.html.slim
- test/doctest/customcss.html
- test/doctest/document.html
- test/doctest/history-regression-tests.html
- test/doctest/history.html
- test/doctest/revealjs-features.html
- test/doctest/revealjs-plugin-activation.html
- test/doctest/revealjs-plugins.html
- test/doctest/theme-custom.html
Add options described in https://github.com/hakimel/reveal.js/#pdf-export
> feat: Add PDF export options

- .travis.yml
jruby-9k seems to provide a version no longer compatible with bundler.
See build failure in #292.
> Attempt at fixing recent Travis JRuby build failures

- templates/section.html.slim
Resolves #273.
With this, it is possible to position background images to the top or bottom of the slide (e.g. to add a banner).
> feat: support data-background-position

- templates/document.html.slim
I was missing quite a bunch of new icons which appeared
in https://fontawesome.com/icons?d=gallery&m=free but
did not work.
This udpates font awesome to the latest CDN-available
version
> feat: upgrade bundled font-awesome from 4.3.0 → 5.8.2

- Rakefile
- examples/multi-destination-content.adoc
> Alternate converter name: reduces surprises and backward compatible

- .gitignore
- HACKING.adoc
Added instructions to handle #265 on future releases and many more little tweaks split by commits.
> Development docs update

- HACKING.adoc
- README.adoc
Created docs in both development and README. Plus, updated the release process.
Fixes #187 
Since this is only docs and not code and I want to release tonight, I'm going to go ahead and merge it. 
This doesn't mean I'm not open to changes or comments, its just that I have a window to release that I don't want to miss. Feel free to comment on this PR and we will open issues or another PR if required.
> Address the Opal and Asciidoctor.js compatibility

- examples/level-sectnums.adoc
- templates/section.html.slim
- test/doctest/level-sectnums.html
- test/doctest/outline.html
- test/doctest/section.html
I found that in helpers.rb the section_title was already defined with sectnum support.
I'm not sure if it is as simple as that, but I changed the section template to use this helper.
> Issue #158: Use section title (with sectnums)

- examples/source-emphasis.adoc
- examples/source-emphasis.css
- templates/asciidoctor-compatibility.css
- test/doctest/source-emphasis.html
> Cancel Asciidoctor line-height in highlight.js table (fixes #331)

- examples/source-emphasis.adoc
- templates/asciidoctor-compatibility.css
- test/doctest/source-emphasis.html
Merge after #334 
* Imported styles from Asciidoctor
* Required an override for bottom border
* Disabled upstream style with a negative margin causing overlap if `.stretched` class is used
> Cosmetic improvements to callout lists

- HACKING.adoc
- README.adoc
Do you think this is enough @robertpanzer or should I do another section as I do for the other tech stacks?
PR fixes #271.
> doc: added link to AsciidoctorJ reveal.js

- Rakefile
> resolves #342 replace pattern with generated code (no substitution)

- examples/mathjax.adoc
- templates/document.html.slim
This PR provides a fix for #348, using a new attribute `mathjaxdir` set in the Asciidoc source.
Thanks to this, the user could for example `npm install mathjax@2.7.7` and then set the `mathjaxdir` attribute: `:mathjaxdir: node_modules/mathjax` to load the library locally instead of from the CDN.
If the attribute is not set, the behaviour is exactly the same as it is currently.
> Fix for issue #348

- examples/grid-layout.adoc
- templates/asciidoctor-compatibility.css
- test/doctest/grid-layout.html
Needed this for a deck. Adding it upstream now and followed bulma's naming (which I didn't use at first).
> Added text-alignment to our column CSS layout

- examples/video.adoc
- templates/video.html.slim
- test/doctest/video.html
iframes requires `allow="autoplay"` HTML attribute to allow content to autoplay now.
It might be a little more complicated since Chrome uses many heuristics to determine if a given domain can or can't autoplay iframes. See  https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#iframe
My experience: using `file:///` URIs to load slidedecks I was never able to get block or inline videos hosted on youtube or vimeo to work reliably in the last few months. This was on both Chromium and Firefox. 
Also, in the meantime, we released 4.0 and `background-video` with autoplay works perfectly (see #316).
So coming back to this problem I diff'ed the iframes from both approaches (one done by reveal.js and the other by us) I found about that `allow="autoplay"` attribute. Adding it to …
> Fixed embedded autoplay videos on Youtube and Vimeo

- examples/video.adoc
- templates/section.html.slim
- test/doctest/video.html
Investigating what I thought was a problem with Asciidoctor, I realize that we are badly loading background-video local files.
Asciidoctor uses the [`media_uri` method](https://github.com/asciidoctor/asciidoctor/blob/bb47c333df0aaab6daefa1f4acd3ba3d2623c0c8/lib/asciidoctor/abstract_node.rb#L325) to lookup video files and we used it in the video template but for `background-video` this wasn't used.
This PR fixes that behavior.
Now, is this a backward-incompatible fix? It could break existing decks that relied on the wrong behavior. However, it was obviously broken and didn't follow what an Asciidoctor/AsciiDoc user would expect. I'm open to make this change part of a feature release but I would find it intense to bump a major version because of this. Guidance needed here.
Note
* Title …
> background-video doesn't honor imagesdir attribute like it should

- README.adoc
Fixes #371
- Introduce a new attribute `uri-revealjs-doc` that points to GitHub v3.9 README.md (note: with 4.0 it will have to point to `uri-revealjs-home`)
- Fix a few broken URLs that were not using the attributes.
> Fix broken documentation links, target reveal-js v3.9 branch

- examples/footnotes.adoc
- templates/asciidoctor-compatibility.css
- templates/helpers.rb
- templates/inline_footnote.html.slim
- templates/section.html.slim
- test/doctest/document.html
- test/doctest/embedded.html
- test/doctest/footnotes.html
It's worth noting that when using reveal.js' default layout (vertically-centered slides), footnotes  will be display just after the content on each slide.
If you want to vertically align footnotes at the bottom of each slides, you will need to provide a custom CSS file. 
resolves #30
> add footnotes (per slide)

- .github/workflows/release.yml
- docs/modules/project/pages/hacking.adoc
- package-lock.json
- package.json
The next step will be to create a Rake (or npm) task to prepare the release and another one to prepare the next release.
We should also create a task to generate the GitHub release from the CHANGELOG. That would probably require to convert the CHANGELOG to Markdown (otherwise we will need to convert it from AsciiDoc to Markdown).
The complete release process:
```
$ bundle exec rake release:prepare 1.2.3
$ git push origin master --tags
$ bundle exec rake release:next 1.2.4
```
> Automate the release process

- asciidoctor-revealjs.gemspec
Seems like they serve no purpose in asciidoctor-reveal.js and most likely are artifacts from ancient Ruby versions
> Drop thread_safe and concurrent-ruby dependencies

- docs/modules/converter/pages/syntax/syntax-highlighting.adoc
The goal for this change is to document how to highlight (parts of) source code blocks. I had a hard time figuring it out if it was possible and how to do it. So hopefully, this will help future users to figure it out more easily.
> Add documentation on how to use highlights

- templates/asciidoctor-compatibility.css
- templates/helpers.rb
- templates/title_slide.html.slim
- test/doctest/document.html
- test/doctest/footnotes.html
- test/doctest/multi-destination-content.html
- test/doctest/revealjs-plugin-activation.html
- test/doctest/revealjs-plugins.html
- test/doctest/title-preamble.html
Should fix https://github.com/asciidoctor/asciidoctor-reveal.js/issues/31 and https://github.com/asciidoctor/asciidoctor-reveal.js/issues/122 , I've adapted the proposed code adapted from what I saw in the html5 converter, tell me if I should adapt the style.
Among the propositions I've used a `br` to separate the authors because a `&middot;` would make the line wraps on my screen, I didn't add a custom class to the `br` because I though the `authors` class of the parent `p` should make it easy enough to customize, but I can change it if you prefer.
> resolves #31 add more complete author information

- docs/modules/converter/pages/syntax/auto-animate.adoc
Adding syntax highlighting, the changes on line with content is because Intellij removes end of line space characters.
> Small doc markup fixes on auto-animate.adoc

- docs/modules/setup/pages/standalone-executable.adoc
took me while to figure out that to actually use the standalone in a standalone manner you should use  
https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.9.0as opposed to look up using npm install etc. 
suggesting to use the cdn  location so the output is standalone and can be run and used with nothing else than the asciidoctor-revealjs binary.
> Mention in the doc that revealjsdir can be a CDN

- templates/document.html.slim
- templates/helpers.rb
Intended to implement https://github.com/asciidoctor/asciidoctor-reveal.js/issues/369
The configuration format changed so I adapted it using https://mathjax.github.io/MathJax-demos-web/convert-configuration/convert-configuration.html and reading the doc.
These are the documents I used for my tests: 
```
= Asciimath
:stem:
== Slide
[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
```
```
= Latexmath no num
:stem: latexmath
== Slide
[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
```
```
= Latexmath num
:stem: latexmath
:eqnums: all
== Slide
[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
[stem]
++++
(a + b)^2 = a^2 + 2ab + b^2
++++
```
```
= Latexmath num ams
firstname1 middlename1 lastname1 <email1@example.net>
2017-01-31
:stem: latexmath
:eqnums: ams
== …
```
> Update MathJax support to version 3

- docs/modules/setup/pages/ruby-setup.adoc
To avoid the deprecated messages:
```
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path '.bundle/gems'`, and stop using this flag
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
```
> Update commands to avoid deprecated messages

- docs/modules/setup/pages/ruby-setup.adoc
* make prerequisites reflect current state of Ruby
* use callout to add note about gem command in Gemfile
* use bundle config to set Bundle install path
* remove unnecessary --binstubs option when calling Bundler
* use presentation.adoc as the sample presentation file name
* fix some inconsistencies with the AsciiDoc syntax
> improve Ruby setup instructions

- docs/modules/setup/pages/ruby-setup.adoc
* make prerequisites reflect current state of Ruby
* use callout to add note about gem command in Gemfile
* use bundle config to set Bundle install path
* add call to bundle
* remove unnecessary --binstubs option when calling Bundler
* use presentation.adoc as the sample presentation file name
* fix some inconsistencies with the AsciiDoc syntax
> resolves #469 improve Ruby set up instructions

- docs/antora.yml
- docs/modules/converter/pages/features.adoc
- docs/modules/converter/pages/syntax/title.adoc
I've added the suggested extra notes and links. The sample-presentation now has an `IMPORTANT` block pointing out the need for proper document structure. It links to the page about the Title Slide. On the Title Slide page, I've added both a good and a bad example of a Document Header and a link to the AsciiDoc page on the Document Header.
I couldn't find how to generate the site to test if my changes looked good. I installed antora, but I might have a newer version as it complains about incorrect configuration. If someone could tell me how to generate the site to verify if links work, I'll gladly do that before finalizing this PR.
I'm looking forward to your review.
> resolves #473 adds extra documentation on document structure and header

- Rakefile
- examples/release-5.2.adoc
- examples/steps.adoc
- src/index.html
- templates/colist.html.slim
- test/doctest/steps.html
Hi,
This PR aims to modify the behavior of the `step` attribute on a callout block. I believe callouts should behave consistently with traditional lists when prefixed with this attribute. 
This adjustment can enhance the presentation of code fragments, offering a more interactive experience.
**Example :**
```asciidoc
[source, javascript]
----
let hello = "hello world"; <1>
console.log(hello); <2>
----
[%step]
<1> First line
<2> Second line
```
In the current implementation, only one fragment would be created. With this modification, individual fragments will be generated for each callout line, aligning with the intended behavior.
**Code :**
On the code side, I've only repositioned the fragment class definition in the colist template and included an example in the `step.adoc` file to …
> Using [%step] on colist works the same as on ulist

- examples/release-5.2.adoc
- lib/asciidoctor-revealjs/highlightjs.rb
- test/doctest/source-highlightjs-languages.html
> Fixes data-fragment-index on code block
