asciidoctor/asciidoctor-reveal.js

templates/slim/document.html.slim
Fixes #14 
Update slim template to look for `highlightjs` to be consistent with Asciidoctor documentation
http://asciidoctor.org/docs/user-manual/#source-code-blocks
=> Update slim template to look for `highlightjs` to be consistent with Asciidoctor documentation

README.adoc
Added a warning to prevent use of reveal.js 3.0.0
=> Warning about version 3 incompatibility

templates/slim/block_admonition.html.slim, templates/slim/document.html.slim
* load FontAwesome from CDN if icons=font
* use local path for FontAwesome if iconfont-remote is unset
* map admonition icon names to FontAwesome icon names
* fix HTML generated for admonition block
=> resolves #24 initial support for font-based icons

HACKING.adoc
Hopefully not offending anyone with duplicating some content here for greater offline availability, also known as plane coding ;)
=> Helpful back-end development tips

README.adoc
functionality implemented with commit c1c17a9e9d88018109a955b5874e304df4df749f
=> example for 'hide title' option

templates/slim/section.html.slim
`====` is rendered to nested section which is not correct.
=> fix unnecessary nested section in vertical sections

templates/slim/document.html.slim
* support background options on title slide
* use h1 for slide title instead of h2
=> resolves #7 support background options on title slide

README.adoc, templates/slim/document.html.slim
Semantic from bespoke back-end:
https://github.com/asciidoctor/asciidoctor-bespoke#the-title-slide
=> Added 'title' class to the title slide to help customize with CSS

HACKING.adoc
Open for comments. Comes from an email discussion between me and @mojavelinux.
=> Formalized a merge / review policy

templates/jade/document.jade
- Fix issue with empty json & use instead empty string
- Resolve https://github.com/asciidoctor/asciidoctor-reveal.js/issues/88
=> Fix issue with empty json & use instead empty string.

HACKING.adoc, README.adoc, asciidoctor-revealjs.gemspec, bin/asciidoctor-revealjs, lib/asciidoctor-revealjs.rb, lib/asciidoctor-revealjs/converter.rb, lib/asciidoctor-revealjs/version.rb, templates/slim/section.html.slim
See #78. This will get updated as I progress.
=> Turning asciidoctor-revealjs into a proper asciidoctor back-end

CHANGELOG.adoc, HACKING.adoc, asciidoctor-revealjs.gemspec, lib/asciidoctor-revealjs/version.rb
Are the changelog and instructions ok?
I have a rubygems.org account now so if you ACK this, I'll tag this commit and push.
=> First release

.travis.yml, Gemfile.upstream
Thanks @mojavelinux to always point in the right direction :smile:
=> Travis: building on asciidoctor's master too (related to #132)

HACKING.adoc, asciidoctor-revealjs.gemspec
Allowing the rubyists a chance to comment
=> More debugging docs

.travis.yml, HACKING.adoc, npm/builder.js, npm/examples.js, package.json
Just a start of javascript testing. People with javascript and npm experience please comment. I borrowed this from Asciidoctor.js and Asciidoctor-template.js.
Tests fail exactly where it should. Waiting on #143 to be fixed.
=> Converting the examples using javascript / node toolchain

README.adoc, Rakefile, examples/README.adoc, examples/source-callouts.adoc, examples/theme-custom.adoc, examples/theme-custom.css, npm/builder.js, package.json, templates/document.html.slim, test/doctest/customcss.html, test/doctest/document.html, test/doctest/history-regression-tests.html, test/doctest/history.html, test/doctest/theme-custom.html
There are a lot of things that've shown up in the reveal.js repo.
This brings in the missing configuration properties here.
=> Sync with Reveal.js 3.5.0

README.adoc
=> Explained that source-highlighter must be defined

CHANGELOG.adoc, README.adoc, examples/background-color.adoc, examples/background-color.css, templates/document.html.slim, test/doctest/background-color.html, test/doctest/customcss.html, test/doctest/document.html, test/doctest/history-regression-tests.html, test/doctest/history.html, test/doctest/revealjs-features.html, test/doctest/revealjs-plugin-activation.html, test/doctest/revealjs-plugins.html, test/doctest/theme-custom.html
Original PR by @mojavelinux here #207.
I had to create a new one because my merge commit made all the changes done before the PR was first created to appear in the review interface. Sorry for the hassle.
=> resolves #16 allow background color of slide to be set using CSS

Gemfile.upstream, asciidoctor-revealjs.gemspec
The PR is because I wanted to see if CI would pass.
=> Asciidoctor 2.0: Dependencies have been updated

README.adoc, templates/document.html.slim, test/doctest/customcss.html, test/doctest/document.html, test/doctest/history-regression-tests.html, test/doctest/history.html, test/doctest/revealjs-features.html, test/doctest/revealjs-plugin-activation.html, test/doctest/revealjs-plugins.html, test/doctest/theme-custom.html
=> Aligned our configuration and documentation to Reveal.js 3.7.0

templates/document.html.slim, templates/section.html.slim
I now - esoteric. But I needed in my presentation…
=> feat: support data-background-opacity via background-opacity

.travis.yml, Rakefile, asciidoctor-revealjs.gemspec, test/asciidoctor-revealjs/custom_templates_test.rb, test/asciidoctor-revealjs/fixtures/templates/paragraph.html.slim, test/asciidoctor-revealjs/version_test.rb, test/test_helper.rb
=> resolves #177 allow to override the built-in slim templates

examples/grid-layout.adoc, templates/asciidoctor-compatibility.css, test/doctest/grid-layout.html
It's a lot prettier when columns are unbalanced.
[Directly inspired by Bulma](https://bulma.io/documentation/columns/options/), good thing you mentioned it in the README @Mogztter!
=> Added is-vcentered to our columns options

examples/images/asciidoctor-logo.svg, examples/release-4.0.adoc, examples/release-4.0.css
Just in case you want to look at it and comment.
My plan is to record a gif of the deck in-action and share it on twitter when I announce the release.
=> Examples: did a promo deck for the 4.0 release

CHANGELOG.adoc, README.adoc
=> Clarified documentation around the --template-dir feature 

templates/video.html.slim
Directly inspired by https://github.com/asciidoctor/asciidoctor/pull/3024/files
=> Videos: added muted options to Vimeo and YouTube embeds

examples/issue-grid-layout-images.adoc, templates/asciidoctor-compatibility.css, test/doctest/issue-grid-layout-images.html
Fixes  #353. Fix provided by @Mogztter.
=> Fix to allow wide images in wrapping columns

.github/workflows/ci.yml
=> resolves #387 add Windows in CI build

examples/grid-layout-3x2.adoc, examples/grid-layout-docinfo-revealjs.html, examples/grid-layout.adoc, templates/asciidoctor-compatibility.css, test/doctest/grid-layout.html
=> resolves #372 move padding inside

examples/text-alignments.adoc, templates/asciidoctor-compatibility.css
=> resolves #380 add text-<alignment> styles

docs/modules/converter/pages/revealjs-options.adoc, examples/custom-layout.adoc, templates/document.html.slim, test/doctest/custom-layout.html, test/doctest/fragments.html, test/doctest/history-hash.html, test/doctest/history-regression-tests.html, test/doctest/history.html, test/doctest/revealjs-plugin-activation.html, test/doctest/revealjs-plugins.html, test/doctest/source-highlightjs-languages.html, test/doctest/theme-custom.html
=> resolves #381 allow to configure disableLayout

examples/font-awesome-specific-version.adoc, examples/font-awesome.adoc, templates/inline_image.html.slim, test/doctest/font-awesome-specific-version.html, test/doctest/font-awesome.html
=> resolves #393 support set attribute on icon

examples/text-formatting.adoc, templates/inline_quoted.html.slim, test/doctest/text-formatting.html
=> Fix subscripts erroneously mapped to superscripts

examples/text-formatting.adoc, templates/inline_quoted.html.slim, test/doctest/text-formatting.html
I found another issue while adding a test!
//cc @9ao9ai9ar :wink:
=> Fix quotation marks and apostrophes

examples/favicon.adoc, templates/document.html.slim, test/doctest/favicon.html
Source of added code can be found in asciidoctor repository
https://github.com/asciidoctor/asciidoctor/blob/3c7d2e8255d2f75dede0aab42ca32948ca4360e4/lib/asciidoctor/converter/html5.rb#L113-L123
rel #419
=> Add favicon to HTML if its attribute is present in AsciiDoc

docs/modules/converter/nav.adoc, docs/modules/converter/pages/syntax/auto-animate.adoc, examples/auto-animate.adoc, templates/section.html.slim
https://revealjs.com/auto-animate/
=> Add support for the Auto-Animate feature introduced in reveal.js 4

CHANGELOG.md, templates/helpers.rb
Update the CHANGELOG.
resolves #432
=> resolves #432 remove the Markdown plugin

CHANGELOG.md, examples/search-plugin.adoc, templates/helpers.rb
=> resolves #433 add support for the built-in search plugin

docs/modules/project/pages/hacking.adoc, docs/modules/setup/pages/ruby-setup.adoc
No content change but small markup fixes so all code is displayed the right way, it was bothering me when I read the doc.
=> Small doc cleaning / improvement

docs/modules/converter/pages/syntax/auto-animate.adoc, docs/modules/converter/pages/syntax/syntax-highlighting.adoc, examples/auto-animate-code.adoc, examples/auto-animate.adoc, lib/asciidoctor-revealjs/highlightjs.rb, templates/asciidoctor-compatibility.css, templates/listing.html.slim
=> resolves #447 support auto-animate on code blocks

docs/modules/converter/pages/revealjs-plugins.adoc, templates/document.html.slim, templates/helpers.rb, test/doctest/custom-layout.html, test/doctest/fragments.html, test/doctest/history-hash.html, test/doctest/history-regression-tests.html, test/doctest/history.html, test/doctest/links-preview.html, test/doctest/revealjs-plugin-activation.html, test/doctest/revealjs-plugins.html, test/doctest/source-highlightjs-languages.html, test/doctest/theme-custom.html
=> resolves #418 use docinfo to declare and configure plugins

docs/modules/setup/pages/standalone-executable.adoc
This pull request is due to this issue: https://github.com/asciidoctor/asciidoctor-reveal.js/issues/500.
=> Add remark about speacker notes to the docs

asciidoctor-revealjs.gemspec, lib/asciidoctor-revealjs/converter.rb
=> resolves #479 upgrade to asciidoctor-templates-compiler 0.7.0
